output   = "models"
add-enum-types = true
wipe     = true
no-tests = true

[psql]
dbname = "skillup"
host   = "localhost"
port   = "5432"
user   = "user"
pass   = "password"
schema = "public"
blacklist = []
sslmode = "disable"


